wwam_core_users:
    pattern:  /users
    defaults: { _controller: WWAMCoreBundle:User:index, _format: json }
    requirements:
      _method: GET
wwam_core_users_get:
    pattern: /users/{id}
    defaults: { _controller: WWAMCoreBundle:User:get, _format: json }
    requirements:
      _method: GET
      id: "\d+"
