parameters:
#    wwam_core.example.class: WWAM\CoreBundle\Example

services:
#    wwam_core.example:
#        class: %wwam_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
